import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { YoutubeExtractor } from './YoutubeExtractor';
import { LlmProcessor } from '../llm/LlmProcessor';

// Load environment variables
const projectRoot = path.resolve(__dirname, '../../../');
const envPath = path.join(projectRoot, '.env');
if (fs.existsSync(envPath)) {
  dotenv.config({ path: envPath });
} else {
  dotenv.config();
}

/**
 * Sanitizes strings so they can be safely used as macOS/Windows filenames.
 */
function sanitizeFilename(name: string): string {
  return name.replace(/[/\\?%*:|"<>]/g, ' ').replace(/\s+/g, ' ').trim();
}

async function main() {
  const args = process.argv.slice(2);
  const urlArgIndex = args.indexOf('--url');
  if (urlArgIndex === -1 || !args[urlArgIndex + 1]) {
    console.error('❌ Usage: npx ts-node ingest-single-youtube.ts --url "<YouTube-URL>"');
    process.exit(1);
  }

  const videoUrl = args[urlArgIndex + 1];
  const videoId = YoutubeExtractor.extractVideoId(videoUrl);
  if (!videoId) {
    console.error('❌ Invalid YouTube URL provided.');
    process.exit(1);
  }

  console.log(`⏳ [BatiFlow YouTube Ingest] Fetching metadata & transcript for video ID: ${videoId}...`);
  
  const extractor = new YoutubeExtractor();
  const llmProcessor = new LlmProcessor();

  try {
    const metadata = await extractor.fetchMetadata(videoId);
    console.log(`✅ Title: "${metadata.title}"`);
    console.log(`✅ Channel: "${metadata.channel}"`);

    const transcript = await extractor.fetchTranscript(videoId);
    console.log('🧠 Processing transcript with DeepSeek Brain Engine...');

    const llmResult = await llmProcessor.analyzeYoutubeTranscript(
      metadata.title,
      metadata.channel,
      `https://www.youtube.com/watch?v=${videoId}`,
      transcript
    );

    if (!llmResult) {
      throw new Error('DeepSeek Brain Engine returned no result.');
    }

    const { analysis, reasoning } = llmResult;

    const cleanChannel = sanitizeFilename(metadata.channel);
    const cleanTitle = sanitizeFilename(metadata.title);
    
    const markdownFilename = `[YouTube] ${cleanChannel} - ${cleanTitle}.md`;
    const traceFilename = `[YouTube] ${cleanChannel} - ${cleanTitle} - reasoning_trace.txt`;

    const todayStr = new Date().toISOString().split('T')[0];
    const vaultBaseDir = process.env.OBSIDIAN_VAULT_PATH || path.join(projectRoot, 'vault');
    const vaultYoutubeDir = path.join(vaultBaseDir, 'YouTube', todayStr);
    if (!fs.existsSync(vaultYoutubeDir)) {
      fs.mkdirSync(vaultYoutubeDir, { recursive: true });
    }

    const vaultMarkdownPath = path.join(vaultYoutubeDir, markdownFilename);
    const vaultTracePath = path.join(vaultYoutubeDir, traceFilename);

    const formattedMarkdown = `---
# 🧠 BatiFlow YouTube Deep Analysis
- **Video Title**: ${metadata.title}
- **Channel**: ${metadata.channel}
- **Original URL**: https://www.youtube.com/watch?v=${videoId}
- **Analysis Date**: ${new Date().toLocaleString('ko-KR', { timeZone: 'Asia/Seoul' })}
- **DeepSeek Reasoning Trace**: [View reasoning_trace.txt](./${encodeURIComponent(traceFilename)})
---

${analysis}

---
*Generated by BatiFlow YouTube Brain Engine v1.0*
`;

    fs.writeFileSync(vaultMarkdownPath, formattedMarkdown, 'utf8');
    fs.writeFileSync(vaultTracePath, reasoning, 'utf8');
    
    // Backup copy
    const scrapYoutubeDir = path.join(projectRoot, `scrap/youtube/${videoId}`);
    if (!fs.existsSync(scrapYoutubeDir)) {
      fs.mkdirSync(scrapYoutubeDir, { recursive: true });
    }
    fs.writeFileSync(path.join(scrapYoutubeDir, 'analysis.md'), formattedMarkdown, 'utf8');
    fs.writeFileSync(path.join(scrapYoutubeDir, 'reasoning_trace.txt'), reasoning, 'utf8');
    fs.writeFileSync(path.join(scrapYoutubeDir, 'transcript.txt'), transcript, 'utf8');

    console.log(`\n🎉 SUCCESS: Saved to Obsidian Vault -> vault/YouTube/${todayStr}/${markdownFilename}`);
    
    // Save to registry
    try {
      const vaultPath = process.env.OBSIDIAN_VAULT_PATH;
      const registryPath = vaultPath && fs.existsSync(vaultPath)
        ? path.join(vaultPath, '.batiflow-registry.json')
        : path.join(projectRoot, 'packages/capture/worker/ingest-registry.json');
      
      let registry = { lastSyncTimestamp: '', processedUrls: {} as Record<string, string> };
      if (fs.existsSync(registryPath)) {
        registry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
      }
      registry.processedUrls[videoUrl] = new Date().toISOString();
      fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2), 'utf8');
      console.log(`[BatiFlow YouTube Ingest] Added URL to sync registry: ${videoUrl}`);
    } catch (err: any) {
      console.warn(`[BatiFlow YouTube Ingest] Failed to update sync registry: ${err.message}`);
    }
    
    // Print summary so calling agent can capture it
    console.log('\n---SUMMARY_START---');
    console.log(analysis.substring(0, 1500) + '\n... (Check Obsidian note for complete report)');
    console.log('---SUMMARY_END---');

  } catch (error: any) {
    console.error(`❌ Ingestion failed: ${error.message}`);
    process.exit(1);
  }
}

main();
