import { chromium } from 'playwright';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { CaptureResult, CaptureData } from '../sources/linkedin/LinkedInCapture';

export class PlaywrightCapture {
  private scrapBaseDir: string;

  constructor(scrapBaseDir?: string) {
    this.scrapBaseDir = scrapBaseDir || path.join(__dirname, '../../../../scrap');
  }

  /**
   * Executes a headless Playwright scraper run.
   */
  public async capture(url: string): Promise<CaptureResult> {
    console.log(`[PlaywrightCapture] Initiating Playwright headless fallback for ${url}...`);
    const startTime = Date.now();
    const steps: string[] = ['Playwright Fallback initiated'];

    let browser;
    try {
      browser = await chromium.launch({ headless: true });
      steps.push('Playwright headless Chromium launched');
      
      const context = await browser.newContext({
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
      });
      const page = await context.newPage();
      
      steps.push(`Navigating to ${url}`);
      await page.goto(url, { waitUntil: 'load', timeout: 30000 });
      
      // Wait for essential DOM structures
      await page.waitForTimeout(3000);
      steps.push('Page loaded, resolving elements');

      // Click "See more" if visible
      const showMoreButton = page.locator('button.feed-shared-inline-show-more-text__button, button.feed-shared-text-view-more-button').first();
      if (await showMoreButton.isVisible()) {
        await showMoreButton.click();
        steps.push('Clicked Show More button');
        await page.waitForTimeout(1500);
      }

      // Extract basic elements
      const data: CaptureData = await page.evaluate(() => {
        const authorEl = document.querySelector('.update-components-actor__name, .update-components-actor__title span[aria-hidden="true"]');
        const author = authorEl ? authorEl.textContent.trim() : 'Unknown Author';

        const headlineEl = document.querySelector('.update-components-actor__description');
        const headline = headlineEl ? headlineEl.textContent.trim() : '';

        const dateEl = document.querySelector('.update-components-actor__sub-text span[aria-hidden="true"]');
        const dateText = dateEl ? dateEl.textContent.trim() : 'Recent';

        const bodyEl = document.querySelector('.feed-shared-update-v2__description-wrapper, .feed-shared-inline-show-more-text');
        const body = bodyEl ? (bodyEl as any).innerText.trim() : 'No content extracted';

        const imgElements = document.querySelectorAll('.update-components-image__image, .update-components-article__image img');
        const images: string[] = [];
        imgElements.forEach((img) => {
          const src = img.getAttribute('src');
          if (src) images.push(src);
        });

        return {
          url: window.location.href,
          author,
          headline,
          dateText,
          body,
          images,
          comments: []
        };
      });

      steps.push('Basic content extracted');

      // Write markdown
      const markdown = `
# LinkedIn Post by ${data.author} (Playwright Fallback)

> **Author Headline**: ${data.headline || 'N/A'}
> **Posted**: ${data.dateText}
> **Source URL**: [View original post](${data.url})

## Post Content

${data.body}

${data.images.length > 0 ? `## Captured Media\n\n` + data.images.map((img, idx) => `![Captured Image ${idx + 1}](${img})`).join('\n\n') : ''}

---
*Generated by BatiFlow v1.0 Playwright Fallback Scraper on ${new Date().toLocaleDateString()}*
`;

      const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');
      const uuid = crypto.randomUUID().slice(0, 8);
      const folderName = `${dateStr}-fallback-${uuid}`;
      const scrapPath = path.join(this.scrapBaseDir, folderName);

      if (!fs.existsSync(scrapPath)) {
        fs.mkdirSync(scrapPath, { recursive: true });
      }

      fs.writeFileSync(path.join(scrapPath, 'post.md'), markdown, 'utf8');
      fs.writeFileSync(path.join(scrapPath, 'extraction.json'), JSON.stringify(data, null, 2), 'utf8');
      steps.push(`Saved fallback scrap to: ${folderName}`);

      const durationMs = Date.now() - startTime;
      return {
        success: true,
        scrapPath,
        data,
        trace: {
          steps,
          timestamp: new Date().toISOString(),
          durationMs
        }
      };

    } catch (err: any) {
      console.error('[PlaywrightCapture] Fallback scraper crashed:', err);
      const durationMs = Date.now() - startTime;
      steps.push(`Fallback scraper crashed: ${err.message}`);
      
      return {
        success: false,
        trace: {
          steps,
          timestamp: new Date().toISOString(),
          durationMs
        }
      };
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }
}
